# Generated by Django 5.0.7 on 2024-08-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Special', '0002_alter_newsimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Спецпроекты', 'verbose_name_plural': 'Спецпроекты'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Изображение Спецпроекты', 'verbose_name_plural': 'Изображения Спецпроекты'},
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
