# Generated by Django 5.0.7 on 2024-08-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_file', models.FileField(upload_to='banners/')),
                ('file_ext', models.CharField(max_length=10)),
                ('file_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(max_length=255, unique=True)),
                ('banner_key', models.CharField(max_length=255, unique=True)),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_link', models.URLField()),
                ('banner_visible', models.BooleanField(default=True)),
                ('banner_date_start', models.DateTimeField()),
                ('banner_date_stop', models.DateTimeField()),
                ('banner_date', models.DateTimeField(auto_now_add=True)),
                ('banner_data', models.JSONField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('files', models.ManyToManyField(blank=True, related_name='banners', to='banner.file')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['banner_date_start'],
            },
        ),
    ]
